# Generated by Django 4.2.30 on 2026-08-20 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('stored_name', models.CharField(max_length=255, unique=True)),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Private'), ('PUBLIC_VIEW', 'Public - View Only'), ('PUBLIC_EDIT', 'Public - Editable')], default='PRIVATE', max_length=20)),
                ('size', models.BigIntegerField()),
                ('checksum', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServerNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, unique=True)),
                ('current_load', models.FloatField(default=0.0)),
                ('active_connections', models.IntegerField(default=0)),
                ('status', models.CharField(default='online', max_length=50)),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('TRANSFERRING', 'Transferring'), ('VERIFYING', 'Verifying'), ('COMPLETE', 'Complete'), ('DISCONNECTED', 'Disconnected'), ('FAILED', 'Failed')], default='PENDING', max_length=50)),
                ('bytes_transferred', models.BigIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='files.file')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.servernode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
